---
- name: creating  directory
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: creating a directory
    file: 
      path: /opt/dir1
      state: directory
      mode: 0755
      owner: ansadmin