---
- name: install and uninstalling multiple packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: install and uninstall packages
    yum:
      name:  "{{ item.package }}"
      state: "{{ item.setup }}"
    loops:
      - { package: 'git', setup: 'installed' }
      - { package: 'make', setup: 'latest' }
      - { package: 'wget', setup: 'removed' }
      - { package: 'tree', setup: 'absent' }


