---
- name: installing package
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed
    notify: start httpd services

  - name: copying index file
    copy:
      src: /home/ansadmin/playbooks/index.html
      dest: /var/www/html

  handlers:
  - name: starting httpd services
    service:
      name: httpd
      state: started
